export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  publishDate: string;
  readTime: string;
  featuredImage: string;
  category: string;
  keywords: string[];
  games?: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "best-arcade-games-houston-texas",
    title: "Best Arcade Games in Houston Texas (2026) | 6 Venues Ranked & Compared",
    description: "Ranked: best arcade games in Houston Texas. Cidercade, Game Preserve, Dave & Buster's, Zero Latency VR. Prices from $12–$50. Full comparison with pros, cons, and who each venue suits best.",
    publishDate: "2026-03-20",
    readTime: "12 min",
    featuredImage: "/hero_img.webp",
    category: "Guides",
    keywords: ["best arcade games houston texas", "arcade games houston texas", "arcades in houston texas"],
  },
  {
    slug: "cidercade-houston-arcade-games-review",
    title: "Cidercade Houston Arcade Games Review | 275+ Games, $12 All-Day, Bar & Pizza",
    description: "Cidercade Houston review: 275+ free-play arcade games, $12 all-day admission, hand-crafted pizza, craft beer bar, East Downtown location. Is it worth it?",
    publishDate: "2026-03-18",
    readTime: "7 min",
    featuredImage: "/outbreak-group-fun.webp",
    category: "Reviews",
    keywords: ["cidercade games houston", "cidercade houston texas", "best arcade games houston texas"],
  },
  {
    slug: "game-preserve-houston-arcade-games-review",
    title: "Game Preserve Houston Arcade Games Review | Retro Games, Pinball, Free Play",
    description: "Game Preserve Houston review: 100+ retro arcade games, pinball machines, $15 day pass, Woodlands and NASA Webster locations. Best retro arcade games in Houston Texas?",
    publishDate: "2026-03-16",
    readTime: "6 min",
    featuredImage: "/post-game-group.jpg",
    category: "Reviews",
    keywords: ["game preserve houston games", "retro arcade games houston texas", "pinball houston texas"],
  },
  {
    slug: "retro-arcade-games-houston-texas",
    title: "Retro Arcade Games Houston Texas | Classic Games, Pinball & Vintage Cabinets (2026)",
    description: "Houston Texas retro arcade games scene: Game Preserve (100+ classics), Cidercade retro section. Where to find pinball machines, Street Fighter cabinets, and vintage gaming in Houston TX.",
    publishDate: "2026-03-14",
    readTime: "8 min",
    featuredImage: "/arena-action.jpg",
    category: "Guides",
    keywords: ["retro arcade games houston texas", "vintage arcade games houston texas", "classic arcade games houston", "pinball houston texas"],
  },
  {
    slug: "arcade-bar-games-houston-texas",
    title: "Arcade Bar Games Houston Texas | Best 18+ Arcades with Drinks (2026)",
    description: "Houston Texas top arcade bars: Cidercade (hard cider + 275 games, 18+ at 9pm), Dave & Buster's (cocktails + sports). Compare drink menus, atmospheres, and age policies.",
    publishDate: "2026-03-12",
    readTime: "7 min",
    featuredImage: "/pvp-experience.webp",
    category: "Guides",
    keywords: ["arcade bar games houston texas", "arcade games houston texas bar", "adult arcade games houston", "18+ arcade games houston texas"],
  },
  {
    slug: "arcade-games-houston-texas-for-kids",
    title: "Arcade Games Houston Texas for Kids | Family-Friendly Guide (2026)",
    description: "Kid-friendly arcade games in Houston Texas: Game Preserve (family-oriented, all ages), Cidercade (daytime family-friendly), Zero Latency VR (Engineerium ages 6+). Pricing and tips for each.",
    publishDate: "2026-03-10",
    readTime: "9 min",
    featuredImage: "/Family-Adventure.webp",
    category: "Guides",
    keywords: ["arcade games houston texas for kids", "arcade games in houston for kids", "family arcade games houston texas", "kid friendly houston texas"],
  },
  {
    slug: "arcade-games-houston-texas-for-adults",
    title: "Arcade Games Houston Texas for Adults | 18+, Bar Arcades & VR (2026)",
    description: "Adult arcade games in Houston Texas: Cidercade 18+ after 9pm with full bar, Dave & Buster's cocktails and sports, Zero Latency VR for groups and date nights. Full comparison.",
    publishDate: "2026-03-08",
    readTime: "8 min",
    featuredImage: "/pvp.webp",
    category: "Guides",
    keywords: ["arcade games houston texas for adults", "arcade games in houston for adults", "houston nightlife arcade games", "adult arcade games houston texas"],
  },
  {
    slug: "free-play-arcade-games-houston-texas",
    title: "Free Play Arcade Games Houston Texas | Unlimited Games from $12 (2026)",
    description: "Free-play arcade games in Houston Texas: Cidercade ($12 all-day, 275+ games) vs Game Preserve ($15 day pass, 100+ retro games). No tokens, no quarters — just press start.",
    publishDate: "2026-03-06",
    readTime: "6 min",
    featuredImage: "/experience.webp",
    category: "Guides",
    keywords: ["free play arcade games houston texas", "unlimited play arcade games houston", "free arcade games houston", "cidercade games houston"],
  },
  {
    slug: "arcade-game-party-venues-houston-texas",
    title: "Arcade Game Party Venues Houston Texas | All Venues Compared (2026 Guide)",
    description: "Houston Texas arcade game birthday party guide: Cidercade party zones, Game Preserve private room ($250), Dave & Buster's packages, Zero Latency VR private arena. Pricing and what's included.",
    publishDate: "2026-03-04",
    readTime: "10 min",
    featuredImage: "/venue-birthday-party.webp",
    category: "Events",
    keywords: ["arcade game birthday party houston texas", "birthday party arcade games houston", "arcade game party houston texas"],
  },
  {
    slug: "bachelor-bachelorette-party-games-houston-texas",
    title: "Bachelor & Bachelorette Party Arcade Games Houston Texas | VR, Bar & Activities",
    description: "Best bachelor and bachelorette party arcade game ideas in Houston Texas: Zero Latency VR adrenaline experience, Cidercade arcade bar, Dave & Buster's dinner and games. Group booking tips.",
    publishDate: "2026-03-02",
    readTime: "7 min",
    featuredImage: "/venue-bachelor-party.webp",
    category: "Events",
    keywords: ["bachelor party arcade games houston", "bachelorette party arcade games houston texas", "group arcade games houston texas"],
  },
  {
    slug: "vr-games-houston-texas",
    title: "VR Arcade Games Houston Texas | Free-Roam Virtual Reality",
    description: "Complete guide to VR arcade games in Houston Texas. Zero Latency Webster, Houston's 8 free-roam multiplayer games explained: pricing, what to expect, how it compares to other options.",
    publishDate: "2026-02-28",
    readTime: "10 min",
    featuredImage: "/venue-arena.webp",
    category: "Guides",
    keywords: ["vr arcade games houston texas", "free roam vr games houston texas", "virtual reality games houston texas"],
  },
  {
    slug: "best-vr-games-houston-texas",
    title: "Best VR Arcade Games in Houston Texas | All 8 Games Ranked",
    description: "All 8 Zero Latency VR arcade games ranked and compared. Player counts, durations, intensity levels, and which game is best for your group — families, adults, competitive players.",
    publishDate: "2026-02-26",
    readTime: "9 min",
    featuredImage: "/experiences-hero.webp",
    category: "Guides",
    keywords: ["best vr games houston texas", "zero latency houston texas games", "vr arcade games houston texas"],
  },
  {
    slug: "zero-latency-houston-vr-games-guide",
    title: "Zero Latency Webster Houston Texas Guide | VR Arcade Games",
    description: "Complete Zero Latency Webster, Houston Texas guide: location, pricing, all 8 VR arcade games, what to expect, booking tips, and 5.0-star review summary. Everything you need before your visit.",
    publishDate: "2026-02-24",
    readTime: "8 min",
    featuredImage: "/Webster_Houston.webp",
    category: "Guides",
    keywords: ["zero latency houston texas", "vr arcade games houston texas", "arcade games houston texas"],
  },
  {
    slug: "fun-things-houston-texas-this-weekend",
    title: "Fun Things to Do in Houston Texas This Weekend | Arcade Games, VR & More (2026)",
    description: "Weekend activities in Houston Texas: 6 arcade game venues, VR gaming, bar arcades, family entertainment. Includes pricing, locations, and what each venue does best.",
    publishDate: "2026-02-22",
    readTime: "10 min",
    featuredImage: "/outbreak-group-fun.webp",
    category: "Houston",
    keywords: ["fun things houston texas", "houston texas arcade games", "arcade games houston texas", "entertainment games houston texas"],
  },
  {
    slug: "activities-clear-lake-houston-tx",
    title: "Activities in Clear Lake Houston TX | Arcade Games, VR & Entertainment",
    description: "Clear Lake Houston TX activities: Zero Latency VR and Game Preserve NASA are both in nearby Webster. Plus dining, outdoor activities, and NASA Space Center.",
    publishDate: "2026-02-20",
    readTime: "8 min",
    featuredImage: "/Webster_Houston.webp",
    category: "Houston",
    keywords: ["activities clear lake houston tx", "clear lake houston texas", "arcade games near me houston"],
  },
  {
    slug: "things-to-do-webster-texas",
    title: "Things to Do in Webster Texas | Arcade Games, VR, Great Wolf Lodge",
    description: "Webster Texas activities: Zero Latency VR arcade games, Game Preserve NASA, and Great Wolf Lodge Northern Lights Arcade — all in one area. Complete guide to Webster entertainment.",
    publishDate: "2026-02-18",
    readTime: "7 min",
    featuredImage: "/venue-lounge-area.webp",
    category: "Houston",
    keywords: ["things to do webster texas", "webster tx arcade games", "arcade games near me houston"],
  },
  {
    slug: "arcade-game-birthday-party-houston",
    title: "Arcade Game Birthday Party Houston | Ideas, Venues & Pricing (2026)",
    description: "Houston arcade game birthday party ideas: Cidercade, Game Preserve, Dave & Buster's, and Zero Latency VR. Pricing, capacity, and what each includes.",
    publishDate: "2026-02-16",
    readTime: "9 min",
    featuredImage: "/party.webp",
    category: "Events",
    keywords: ["arcade game birthday party houston", "birthday party arcade games houston", "arcade game party houston texas"],
  },
  {
    slug: "houston-team-building-arcade-games",
    title: "Houston Team Building Arcade Games | VR, Corporate Events & Activities",
    description: "Houston corporate team building with arcade games: Zero Latency VR co-op missions and PvP tournaments, Dave & Buster's private rooms, Cidercade group outings. Pricing and booking guide.",
    publishDate: "2026-02-14",
    readTime: "8 min",
    featuredImage: "/venue-team-building.webp",
    category: "Events",
    keywords: ["houston team building arcade games", "corporate events arcade games houston", "group arcade games houston texas"],
  },
  {
    slug: "houston-date-night-arcade-games",
    title: "Houston Date Night Arcade Games | Bar Arcades, VR & More (2026)",
    description: "Houston date night arcade games: Cidercade arcade bar (18+, pizza, craft beer), Zero Latency VR (adrenaline date), Dave & Buster's Date Night Duo. Best options by budget and vibe.",
    publishDate: "2026-02-12",
    readTime: "7 min",
    featuredImage: "/pvp-experience.webp",
    category: "Houston",
    keywords: ["houston date night arcade games", "arcade games date night houston", "houston date night", "arcade bar games houston texas"],
  },
  {
    slug: "arcade-games-group-activities-houston",
    title: "Arcade Games Group Activities Houston TX | Venues, VR & Party Options",
    description: "Group arcade game activities in Houston: arcade parties, VR team games, bar arcade outings. All venues compared by group size, pricing, and what makes each one worth booking.",
    publishDate: "2026-02-10",
    readTime: "8 min",
    featuredImage: "/post-game-group.jpg",
    category: "Events",
    keywords: ["arcade games group activities houston", "houston entertainment games", "arcade games houston texas"],
  },
];

export function getAllBlogPosts(): BlogPost[] {
  return blogPosts;
}

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}
